name = "racer159-net"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2022-02-12"

[site]
bucket = "./public"
entry-point = "./dist"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
